version: "3.9"

services:
  postgres:
    image: postgres
    container_name: shop_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    volumes:
      - /var/data/postgres:/var/lib/postgresql/data
    networks:
      - shop_network
    restart: always

  redis:
    image: redis
    container_name: shop_redis
    networks:
      - shop_network
    restart: always

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: shop_django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - shop_network
    restart: always

networks:
  shop_network:
    driver: bridge