# Generated by Django 3.2 on 2022-07-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='step',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('paid', 'Paid')], default='initial', max_length=20, verbose_name='Step'),
        ),
    ]
