# Generated by Django 3.2 on 2022-07-23 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}(?:-[0-9]{4})?$')], verbose_name='Zip code'),
        ),
    ]
