# Generated by Django 3.2 on 2022-07-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('carts', '0008_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discountcode', verbose_name='Discount code'),
        ),
    ]
