# Generated by Django 3.2 on 2022-07-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Final price'),
        ),
    ]
